DNL:

  SEPARATE_SEARCH_SCHEDULER: True
  SEPARATE_SEARCH_STEPS: [200, 300]

  LEARN_LENGTH: True
  LEARN_STARTPOS: True
  LENGTH_LR: 3.0

  VCH_nls: 2




  LR_SCHEDULER: 'WarmupMultiStepLR'
  INIT_AFTER_SEARCH: True

  SEPARATE_TRAINING: True
  MAX_SEARCH_EPOCH: 400
  ITER_EPOCH_NUM: 10
  WEIGHT_FACTOR: 0.5

  STARTPOS_LR: 3.0

  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  OPTIMIZER_TYPE: 'SGD'
  STEPS: [100, 200, 300]
  WARMUP_METHOD: 'linear'
  GAMMA: 0.5


MODEL:
  DNL: True
  DOUBLE_CH: True
  DOUBLE_SP: True
  BACKBONE_PRETRAIN: False




  PRETRAIN_CHOICE: 'imagenet'
  NAME: 'mobilenetv2_53_DSP_VCH'
  LAST_STRIDE: 1
  PRETRAIN_PATH: 'no'
  METRIC_LOSS_TYPE: 'triplet_center'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'yes'
  LOSS_BRANCH: 1
  NECK: 'bnneck'
  FEAT_DIM: 1280
  COMPUTE_MODEL_COMPLEXITY: False


INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10


DATASETS:
  NAMES: ('market1501')
  ROOT_DIR: ('/home/ywan1053/reid-strong-baseline-master/data')


DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8


SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 1400
  BASE_LR: 0.035

  CLUSTER_MARGIN: 0.3

  CENTER_LR: 0.5
  CENTER_LOSS_WEIGHT: 0.0005

  RANGE_K: 2
  RANGE_MARGIN: 0.3
  RANGE_ALPHA: 0
  RANGE_BETA: 1
  RANGE_LOSS_WEIGHT: 1
  POSITION_LR_FACTOR: 1.0
  WEIGHT_DECAY_POSITION: 0.0005

  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  STEPS: [801, 1001, 1201, 1301]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 40
  LOG_PERIOD: 20
  EVAL_PERIOD: 20


TEST:
  IMS_PER_BATCH: 128
  RE_RANKING: 'no'
  WEIGHT: "path"
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'
  IF_WDB: True
  WDB_PROJECT: 'final_version'
  WDB_NAME: 'mobilenetv2_53_DSP_VCH_DNL_SGD'
  WDB_PRINT_POSITION: True
  WDB_PRINT_ITER: True

GRADCAM:
  TARGET_LAYER_NAMES: "conv"
  MODEL_WEIGHT_PATH: '/data/yyang409/yancheng/log/market1501/dnl/both_new/mobilenetv2_53_DSP_VCH_DNL_SGD/mobilenetv2_53_DSP_VCH_model_1400.pth'
  IMAGE_SIZE: (128, 256)
  USE_GT_LABEL: True
  SET_TARGET_INDEX: False
  TARGET_CLASS_INDEX: 0
  OUT_PATH: '/home/ywan1053/reid-strong-baseline-master/grad_cam/mobilenetv2_53_DSP_VCH_DNL_SGD/featureMap'

OUTPUT_DIR: "/data/yyang409/yancheng/log/market1501/dnl/both_new/mobilenetv2_53_DSP_VCH_DNL_SGD"



